services:
  ocular:
    image: ghcr.io/simonwep/ocular:v2
    restart: unless-stopped
    volumes:
      - ./data:/data/genesis
    command: start
    environment:
      - GENESIS_JWT_SECRET
      - GENESIS_CREATE_USERS
      - GENESIS_JWT_TOKEN_EXPIRATION
